### PR TITLE
add a function to handle deleted channels

### PR DESCRIPTION
**Pull request by hugurp**
when channels are deleted, delete the reference of themselves, into the favorites of other people

### CODE REVIEW

**Comment by oskarrough** [comment]
Huge news! This will fix https://github.com/internet4000/radio4000/issues/70.

While doing this, we did a lot of database moving around with the Firebase CLI. We should save/alias those scripts for later. Should we put them in the gitlab backend repo or here?

**Comment by hugurp** [comment]
yes! let's have those utility scripts saved there, which is a pretty clean spot.

**Comment by oskarrough** [comment]
https://gitlab.com/internet4000/radio4000-admin-backend-express/merge_requests/2

**Comment by hugurp** [comment]
yolo this is deploy as a function on the live db
and now merging

missing the clean db script from the other admin repo

**Pull request merged**
