### PR TITLE
WIP Setup CI

### PR DESCRIPTION
**Pull request by oskarrough**
Hey, this lints using xo (I used `xo --fix` and then ran through it quickly) and sets up ci tests on Travis, which would later lead to deployment as well.

Still need to make sure travis runs. It needs a pull request before it starts, I think.

### CODE REVIEW

**Comment by hellerve** [comment]
I would suggest against using XO. It has horrible defaults and does not conform to any of the common style guides.

I'm not going in a tabs vs. spaces war (spaces guy here), but XO doesn't even respect the simple rule of tabs guys (`tabs for indentation, spaces for alignment`). It is not to be trusted.

Travis also seems to have trouble, but I can't access the build log.

**Comment by oskarrough** [comment]
OK, I'll close.

**Comment by hellerve** [comment]
I would say we should have an ongoing discussion about code style, formatting, and CI, though. Although at the moment We don't have any tests, so I'm not sure how it is helpful.

**Comment by hugovieilledent** [comment]
I am completely lost with tabs, spaces, editorconfigs.
Please just choose something to the editor config that will make eeryone comply.

**Comment by hellerve** [comment]
I don't really care either. I just normally use the standard (i.e. PEP-8 in Python, gofmt in Go, et.c). The problem is that JavaScript does not really have a consensus, AFAIK.

**Pull request closed without merging**
